#!/usr/bin/env bash

set -e

quiet=""
output="output"
if [ "$1" = "-q" ] ; then
    shift
    quiet="1"
    output="output-local"
    export OVERRIDE_SITEURL=http://blog.localhost:8000
fi

echo -n "regenerating..."
if [[ -e "$output/drafts" ]] ; then
    rm -r $output/drafts/
    mkdir $output/drafts
fi
~/src/blog/.venv/bin/pelican content/ -o $output -s pelicanconf.py "$@"
(
    cd $output/drafts
    for F in * ; do
      echo "<a href=\"$F\">$F</a><br>"
    done
) > $output/drafts/list.html

rm $output/category/"{slug}"*.html

(
    cd archive
    rsync -r . ../$output/archive
)

echo "hiya" > $output/drafts/index.html
cp content/favicon.ico content/Ian_Bicking_resume.pdf $output/
echo done.

if [ "$quiet" = "" ] ; then
    echo -n "rsyncing..."
    # rsync -r output/ blog.ianbicking.org:ianbicking.org/
    rsync -r --delete output/* publish-branch
    echo done.
    echo "Commit the files in publish-branch/ to publish"
fi
