#!/usr/bin/env bash

set -e

quiet=""
output="output"
if [ "$1" = "-q" ] ; then
    shift
    quiet="1"
    output="output-local"
    export OVERRIDE_SITEURL=http://blog.localhost
fi

echo -n "regenerating..."
if [[ -e "$output/drafts" ]] ; then
    rm -r $output/drafts/
    mkdir $output/drafts
fi
~/.virtualenvs/blog/bin/pelican content/ -o $output -s pelicanconf.py "$@"
(
    cd $output/drafts
    for F in * ; do
      echo "<a href=\"$F\">$F</a><br>"
    done
) > $output/drafts/list.html
echo "hiya" > $output/drafts/index.html
echo done.

if [ "$quiet" = "" ] ; then
    echo -n "rsyncing..."
    rsync -r output/ blog.ianbicking.org:ianbicking.org/
    echo done.
fi
